import toyota_fortunar from "../../../assets/toyota-fortuner_930x620.jpg";

const sampleReport = {
  bookingId: "PUN2105000001",
  customerName: "Sahil Theurkar",
  engineer_name: "Rohit Mandhare",
  date: "2025-04-01",
  engineer_assignedSlot: "09:00 AM - 10:00 AM",
  address: "Pune",
  brand: "Toyota",
  model: "Fortuner",
  carStatus: "New",
  vinNumber: "MBJ123456KJX98765",
  variant: "4×4 AT 2.8 Diesel",
  transmissionType: "Automatic",
  fuelType: "Diesel",
  engineNumber: "1GD1234567",
  keys: "2",
  vehicleScore: 9.5,
  scoreComment: "The vehicle is in excellent condition with no defects.",
  kmsDriven: 75,
  avgRunning: 60,
  tamperingStatus: "No Tampering",
  BHPs: 203,
  Airbags: 8,
  NCAP: "5 Star",
  Mileage: "14.5 kmpl",
  imageUrl: toyota_fortunar,
  front_left_imageUrl: toyota_fortunar,
  rear_left_imageUrl: toyota_fortunar,
  rear_right_imageUrl: toyota_fortunar,
  front_right_imageUrl: toyota_fortunar,

  bonnet_paintThickness: 0.14,
  bonnet_issues: ["Small scratch near edge"],
  bonnet_repaint: false,
  bonnet_imageUrls: [toyota_fortunar],

  bumper_paintThickness: 0.16,
  bumper_issues: [],
  rear_bumper_repaint: true,
  rear_bumper_imageUrls: {toyota_fortunar},

  front_left_fender_paintThickness: 0.12,
  front_left_fender_issues: ["Dent near wheel arch"],
  front_left_fender_cladding_issues: ["Cladding misaligned"],
  front_left_fender_repaint: false,
  front_left_fender_imageUrls: [toyota_fortunar],

  front_left_door_paintThickness: 0.15,
  front_left_door_issues: ["Scratch near handle"],
  front_left_door_cladding_issues: [],
  front_left_door_repaint: true,
  front_left_door_imageUrls: [toyota_fortunar, toyota_fortunar],

  rear_left_door_paintThickness: 0.13,
  rear_left_door_issues: [],
  rear_left_door_cladding_issues: [],
  rear_left_door_repaint: false,
  rear_left_door_imageUrls: [],

  rear_left_quarter_panel_paintThickness: 0.14,
  rear_left_quarter_panel_issues: [],
  rear_left_quarter_panel_cladding_issues: [],
  rear_left_quarter_panel_repaint: false,
  rear_left_quarter_panel_imageUrls: [],

  boot_paintThickness: 0.17,
  boot_issues: ["Minor chip"],
  boot_imageUrls: [toyota_fortunar],
  rear_bumper_paintThickness: 0.15,
  rear_bumper_issues: [],
  rear_bumper_repaint: false,
  rear_bumper_imageUrls: [],

  rear_right_quarter_panel_paintThickness: 0.14,
  rear_right_quarter_panel_issues: ["Rust spot"],
  rear_right_quarter_panel_cladding_issues: [],
  rear_right_quarter_panel_repaint: true,
  rear_right_quarter_panel_imageUrls: [toyota_fortunar],

  rear_right_door_paintThickness: 0.13,
  rear_right_door_issues: [],
  rear_right_door_cladding_issues: [],
  rear_right_door_repaint: false,
  rear_right_door_imageUrls: [],

  front_right_door_paintThickness: 0.15,
  front_right_door_issues: ["Paint peel near mirror"],
  front_right_door_cladding_issues: [],
  front_right_door_repaint: true,
  front_right_door_imageUrls: [toyota_fortunar],

  front_right_fender_paintThickness: 0.12,
  front_right_fender_issues: [],
  front_right_fender_cladding_issues: [],
  front_right_fender_repaint: false,
  front_right_fender_imageUrls: [],

  roof_paintThickness: 0.14,
  roof_issues: [],
  roof_repaint: false,
  roof_imageUrls: [],

  front_windshield_brand: "Pilkington",
  front_windshield_manufacturingDate: "2024-06-15",
  front_windshield_issues: [],
  front_windshield_imageUrls: [],

  front_left_door_glass_brand: "Saint-Gobain",
  front_left_door_glass_manufacturingDate: "2024-06-10",
  front_left_door_glass_issues: [],
  front_left_door_glass_imageUrls: [],

  left_side_orvm_brand: "OEM",
  left_side_orvm_manufacturingDate: "2024-06-01",
  left_side_orvm_issues: [],
  left_side_orvm_imageUrls: [],

  rear_left_door_glass_brand: "Saint-Gobain",
  rear_left_door_glass_manufacturingDate: "2024-06-10",
  rear_left_door_glass_issues: [],
  rear_left_door_glass_imageUrls: [],

  rear_left_quarter_glass_brand: "OEM",
  rear_left_quarter_glass_manufacturingDate: "2024-06-12",
  rear_left_quarter_glass_issues: [],
  rear_left_quarter_glass_imageUrls: [],

  rear_windshield_brand: "Pilkington",
  rear_windshield_manufacturingDate: "2024-06-15",
  rear_windshield_issues: [],
  rear_windshield_imageUrls: [],

  rear_right_quarter_glass_brand: "OEM",
  rear_right_quarter_glass_manufacturingDate: "2024-06-12",
  rear_right_quarter_glass_issues: [],
  rear_right_quarter_glass_imageUrls: [],

  rear_right_door_glass_brand: "Saint-Gobain",
  rear_right_door_glass_manufacturingDate: "2024-06-10",
  rear_right_door_glass_issues: [],
  rear_right_door_glass_imageUrls: [],

  front_right_door_glass_brand: "Saint-Gobain",
  front_right_door_glass_manufacturingDate: "2024-06-10",
  front_right_door_glass_issues: [],
  front_right_door_glass_imageUrls: [],

  right_side_orvm_brand: "OEM",
  right_side_orvm_manufacturingDate: "2024-06-01",
  right_side_orvm_issues: [],
  right_side_orvm_imageUrls: [],

  sunroof_glass_brand: "OEM",
  sunroof_glass_manufacturingDate: "2024-06-15",
  sunroof_glass_issues: [],
  sunroof_glass_imageUrls: [],

  rubber_bonnet_issues: [],
  rubber_front_left_door_issues: ["Worn out"],
  rubber_rear_left_door_issues: [],
  rubber_boot_issues: [],
  rubber_rear_right_door_issues: [],
  rubber_front_right_door_issues: [],
  rubber_front_wiper_issues: [],
  rubber_rear_wiper_issues: [],
  rubber_rear_wiper_toggle: true,
  rubber_sunroof_issues: [],

  seat_driver_issues: ["Minor stain"],
  seat_driver_imageUrls: [toyota_fortunar],
  seat_driver_head_rest_issues: [],
  seat_driver_head_rest_imageUrls: [],
  seat_codriver_issues: [],
  seat_codriver_imageUrls: [],
  seat_codriver_head_rest_issues: [],
  seat_codriver_head_rest_imageUrls: [],
  seat_rear_issues: ["Torn fabric"],
  seat_rear_imageUrls: [toyota_fortunar],
  seat_rear_head_rest_issues: [],
  seat_rear_head_rest_imageUrls: [],
  seat_third_row_issues: [],
  seat_third_row_imageUrls: [],
  seat_third_row_toggle: true,
  seat_third_row_head_rest_issues: [],
  seat_third_row_head_rest_imageUrls: [],
  seat_roof_issues: [],
  seat_roof_imageUrls: [],
  seat_sunroof_issues: [],
  seat_sunroof_imageUrls: [],

  seatbelt_driver_issues: [],
  seatbelt_driver_imageUrls: [],
  seatbelt_codriver_issues: [],
  seatbelt_codriver_imageUrls: [],
  seatbelt_rear_left_passenger_issues: [],
  seatbelt_rear_left_passenger_imageUrls: [],
  seatbelt_rear_right_passenger_issues: [],
  seatbelt_rear_right_passenger_imageUrls: [],
  seatbelt_third_row_issues: [],
  seatbelt_third_row_imageUrls: [],
  seatbelt_third_row_toggle: false,

  plastic_driver_door_issues: [],
  plastic_driver_door_imageUrls: [],
  plastic_codriver_door_issues: ["Loose fitting"],
  plastic_codriver_door_imageUrls: [toyota_fortunar],
  plastic_rear_left_passenger_door_issues: [],
  plastic_rear_left_passenger_door_imageUrls: [],
  plastic_rear_right_passenger_door_issues: [],
  plastic_rear_right_passenger_door_imageUrls: [],
  plastic_third_row_issues: [],
  plastic_third_row_imageUrls: [],
  plastic_third_row_toggle: true,
  plastic_dashboard_issues: [],
  plastic_dashboard_imageUrls: [],
  plastic_gear_console_issues: [],
  plastic_gear_console_imageUrls: [],
  plastic_steering_issues: [],
  plastic_steering_imageUrls: [],
  plastic_ac_vents_issues: [],
  plastic_ac_vents_imageUrls: [],
  plastic_rear_ac_vents_issues: [],
  plastic_rear_ac_vents_imageUrls: [],
  plastic_irvm_issues: [],
  plastic_irvm_imageUrls: [],

  feature_parking_sensors_front_available: true,
  feature_parking_sensors_front_issueObserved: false,
  feature_parking_sensors_rear_available: true,
  feature_parking_sensors_rear_issueObserved: false,
  feature_front_view_camera_available: true,
  feature_front_view_camera_issueObserved: false,
  feature_rear_view_camera_available: true,
  feature_rear_view_camera_issueObserved: false,
  feature_camera_360_available: false,
  feature_camera_360_issueObserved: false,
  feature_touch_screen_available: true,
  feature_touch_screen_issueObserved: false,
  feature_speakers_available: true,
  feature_speakers_issueObserved: false,
  feature_electric_orvm_available: true,
  feature_electric_orvm_issueObserved: false,
  feature_auto_dimming_irvm_available: false,
  feature_auto_dimming_irvm_issueObserved: false,
  feature_ventilated_seat_driver_available: true,
  feature_ventilated_seat_driver_issueObserved: false,
  feature_ventilated_seat_codriver_available: true,
  feature_ventilated_seat_codriver_issueObserved: false,
  feature_ventilated_seat_rear_available: false,
  feature_ventilated_seat_rear_issueObserved: false,

  live_engine_load_toggle: true,
  live_engine_load: "30%",
  live_idle_rpm_toggle: true,
  live_idle_rpm: 750,
  live_battery_voltage: "12.6V",
  live_distance_since_code_clear: 1020,
  live_distance_in_current_lock_block: 250,

  engine_issues: "None",
  transmission_issues: "None",
  brakes_issues: "None",
  diagnostic_codes: [],

  fluid_coolant_withinRange: true,
  fluid_coolant_contamination: false,
  fluid_engineOil_withinRange: true,
  fluid_engineOil_contamination: false,
  fluid_brakeOil_withinRange: true,
  fluid_brakeOil_contamination: false,
  fluid_washerFluid_withinRange: true,
  fluid_washerFluid_contamination: false,

  tyre_front_left_brand: "Michelin",
  tyre_front_left_subBrand: "Pilot Sport",
  tyre_front_left_variant: "PS4",
  tyre_front_left_issues: [],
  tyre_front_left_size: "225/45 R17",
  tyre_front_left_treadDepth: 7.6,
  tyre_front_left_manufacturingDate: "2024-03-12",
  tyre_front_left_imageUrls: [toyota_fortunar],

  tyre_rear_left_brand: "Michelin",
  tyre_rear_left_subBrand: "Pilot Sport",
  tyre_rear_left_variant: "PS4",
  tyre_rear_left_issues: [],
  tyre_rear_left_size: "225/45 R17",
  tyre_rear_left_treadDepth: 7.5,
  tyre_rear_left_manufacturingDate: "2024-03-12",
  tyre_rear_left_imageUrls: [],

  tyre_rear_right_brand: "Michelin",
  tyre_rear_right_subBrand: "Pilot Sport",
  tyre_rear_right_variant: "PS4",
  tyre_rear_right_issues: ["Small cut"],
  tyre_rear_right_size: "225/45 R17",
  tyre_rear_right_treadDepth: 6.0,
  tyre_rear_right_manufacturingDate: "2024-03-12",
  tyre_rear_right_imageUrls: [],

  tyre_front_right_brand: "Michelin",
  tyre_front_right_subBrand: "Pilot Sport",
  tyre_front_right_variant: "PS4",
  tyre_front_right_issues: [],
  tyre_front_right_size: "225/45 R17",
  tyre_front_right_treadDepth: 7.6,
  tyre_front_right_manufacturingDate: "2024-03-12",
  tyre_front_right_imageUrls: [],

  tyre_spare_brand: "Michelin",
  tyre_spare_subBrand: "Pilot Sport",
  tyre_spare_variant: "PS4",
  tyre_spare_issues: [],
  tyre_spare_size: "225/45 R17",
  tyre_spare_treadDepth: 8.0,
  tyre_spare_manufacturingDate: "2023-12-01",
  tyre_spare_imageUrls: [],
  tyre_spare_toggle: true,

  other_observations: "No abnormal noise observed during inspection.",
};

export default sampleReport;